### ISSUE TITLE
Concordance entries match as substrings

### ISSUE THREAD

**Issue by sethmisenar** [joswr1ght/pptxindex#5]
Sometimes this feels like a feature and other times like a bug. The concordance entries do not match only whole words or phrases. Rather they will match even if the entry is just a substring. For example with the following entry I am trying to find **`apt`**, the command. However, I could end up matching on the word **`Captive`**.

``` python
apt; "apt" in cspage
```

The upside to this behavior is that simple plurals of **`s`** or **`es`** are automatically captured by the same logic. So, again, not sure if this is a feature or a bug; I guess it just depends on the expected behavior. My expectation was, and preference would be, to have the terms explicitly match rather than simply be substrings of a word or phrase.

**Comment by joswr1ght** [comment]
I'm not sure how to address this.  You can always preface the string to match with a space to avoid "apt" matching "captive": `APT; " apt" in page`.  I imagine though that when you do case-sensitive searching for an acronym like APT, you would use the case-sensitive page matching to avoid partial matches: `APT; "APT" in cspage`.

I could always expose a variable (let's call it `wordlist`) that returns a list of individual words that you match only by whole word:

```
>>> s="Windows Server Update Services (WSUS), which replaced the earlier Software Update Services (SUS), is Microsoft’s free server that can be leveraged to serve as an organization’s internal, self-managed, version of Windows Update. WSUS provides a centrang updates to Windows, Office, as well as most other Microsoft products."
>>> import re
>>> wordlist=re.split("(?:(?:[^a-zA-Z]+')|(?:'[^a-zA-Z]+))|(?:[^a-zA-Z']+)", s)
>>> wordlist
['Windows', 'Server', 'Update', 'Services', 'WSUS', 'which', 'replaced', 'the', 'earlier', 'Software', 'Update', 'Services', 'SUS', 'is', 'Microsoft', 's', 'free', 'server', 'that', 'can', 'be', 'leveraged', 'to', 'serve', 'as', 'an', 'organization', 's', 'internal', 'self', 'managed', 'version', 'of', 'Windows', 'Update', 'WSUS', 'provides', 'a', 'central', 'console', 'for', 'pushing', 'updates', 'to', 'Windows', 'Office', 'as', 'well', 'as', 'most', 'other', 'Microsoft', 'products', '']
>>> "WSUS" in wordlist
True
```

This would not accommodate plural matching without punctuation ("WSUSs", which looks weird), but it would match "WSUS's" since the "'s" would get split from the original.

Would this help? It's easy enough to add, though I worry a little about making too many options for concordance matching that it becomes confusing.  Let me know.  Thanks!

**Comment by sethmisenar** [comment]
I think exposing a `wordlist` variable would be straightforward enough, and help to address what I was experiencing. It might be worthwhile to name it something like `csword` or `cswordlist`, which is a bit lengthy, to indicate the case sensitive nature of the wordlist.

Especially after the enhancement in issue https://github.com/joswr1ght/pptxindex/issues/3 is addressed, my planned flow, assuming the `in wordlist` enhancement, would be to build a concordance first using simple `in page` matches. Then, if hitcounts are too high, look to see if `in cspage` or `in wordlist` might resolve the reason for the high hitcount.
